image_width: 640
image_height: 480
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [735.48343,   0.     , 334.87545,
          0.     , 736.20036, 240.99101,
          0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.086527, -0.363703, -0.004697, -0.003552, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
        0., 1., 0.,
        0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [738.51565,   0.     , 333.683  ,   0.     ,
          0.     , 740.92898, 239.76581,   0.     ,
          0.     ,   0.     ,   1.     ,   0.     ]